config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'homes/top'
  root :to => 'homes#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users
  resources :books
  get '/home/about' =>"homes#about"
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  
  validates :body, length: { maximum: 200 }

  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  
  before_action :correct_user, only: [:edit, :update]

  def top
  end

  def index
    @user = current_user
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @user = current_user
      @books = Book.all
      render :index
    end
  end

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
  end

  def edit
    @book = Book.find(params[:id])
  end
  
  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    flash[:notice] = "You have updated book successfully."
    redirect_to book_path(@book.id) 
    else
    render :edit
    end
  end
  
  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

private

  def book_params
    params.require(:book).permit(:title, :body)
  end
  
  def correct_user
    @book = Book.find(params[:id])
    @user = @book.user
    redirect_to(books_path) unless @user == current_user
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<!--book編集-->

    <div class="container">
      <div class="row">
        <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
          
          <h1>Editing Book</h1>
          
          <% if @book.errors.any? %>
          <%= @book.errors.count %>errors prohibited this book from being saved:
          <ul>
            <% @book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
          <% end %>
          
          <%= form_with model: @book, url: book_path(@book.id), method: :patch do |f| %>
          <div class="form-group">
            <h4>Title</h4>
            <%= f.text_field :title  %>
          </div>
          <div class="form-group">
            <h4>Opinion</h4>
            <%= f.text_area :body %>
          </div>
          <%= f.submit 'Update Book', class: "btn btn-success" %>
          <% end %>
          
          <%= link_to "Show",book_path(@book.id) %> | <%= link_to "Back",books_path %> 
          
        </div>
      </div>
    </div>

app/views/books/index.html.erb
<!--すべてのBooks-->
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render "layouts/userinfo", user: @user, book: @book %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to user_path(book.user) do %>
              <%= image_tag book.user.get_profile_image(80,80) %>
              <% end %>
            </td>
            <td>
              <%=link_to book.title, book_path(book) %>
            </td>
            <td>
              <%= book.body %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h

app/views/books/show.html.erb
<!--book詳細-->
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <%= render "layouts/userinfo", user: @user, book: @book_new %>
    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table">
        <tbody>
          <tr>
            <td><%= link_to user_path(@book.user) do %>
            <%= image_tag @book.user.get_profile_image(100,100) %><br>
            <%= @book.user.name %>
            <% end %>
            </td>
            <td><%= link_to @book.title, book_path(@book.id) %></td>
            <td><%= @book.body %></td>
            <% if @book.user == current_user %>
            <td><%= link_to "Edit", edit_book_path(@book.id), class: "btn btn-sm btn-success" %></td>
            <td><%= link_to "Destroy", book_path(@book.id), class: "btn btn-sm btn-danger" ,method: :delete, "data-confirm" => "本当に削除しますか？" %></td>
            <% end %>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/top.html.erb
<h1>Books#top</h1>
<p>Find me in app/views/homes/top.html.erb</p>