config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'homes/top'
  root :to => 'homes#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users
  resources :books
  get '/home/about' =>"homes#about"
end

app/views/layouts/_userinfo.html.erb
          <h2>User info</h2>
          <%= image_tag @user.get_profile_image(80,80) %>
          <table class="table">
            <tbody>
              <tr>
                <th>name</th>
                <td><%= user.name %></td>
              </tr>
              <tr>
                <th>introduction</th>
                <td><%= user.introduction %></td>
              </tr>
            </tbody>
          </table>
          <div class="row">
            <%= link_to edit_user_path(user.id), class: "btn btn-outline-secondary btn-block" do %>
             <i class="fas fa-user-cog"></i>
            <% end %>
          </div>
      
      <h2 class="mt-3">New book</h2>
      
      <% if book.errors.any? %>
      <%= book.errors.count %>errors prohibited this book from being saved:
      <ul>
        <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
      <% end %>
      
      <%= form_with model: book, url: '/books', method: :post do |f| %>
      <h4>title</h4>
      <%= f.text_field :title %>
      
      <h4>Opinion</h4>
      <%= f.text_area :body %>
      <%= f.submit 'Create Book', class: "btn btn-success" %>
      <% end %>

app/views/layouts/application.html.erb
<html>
  <head>
    <title>Bookers2</title>
    <!--<meta name="viewport" content="width=device-width,initial-scale=1">-->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
          <%= link_to "Bookers",root_path, class:"navbar-brand" %>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                         aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to user_path(current_user.id), class: 'nav-link text-light' do %>
                  <i class="fas fa-home"></i>Home
                 <% end %>
              </li>
              <li class="nav-item">
                <%= link_to users_path, class: 'nav-link text-light' do %>
                   <i class="fas fa-users"></i>Users
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to books_path, class: 'nav-link text-light' do %>
                 <i class="fas fa-book-open"></i>Books
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-light' do %>
                 <i class="fas fa-sign-out-alt"></i>Log out
                <% end %>
              </li>
              <% else %>
              <li class="nav-item">
                <%= link_to root_path, class: 'nav-link text-light' do %>
                <i class="fas fa-home"></i>Home
              <% end %>
              </li>
              <li class="nav-item">
                <%= link_to home_about_path, class: 'nav-link text-light' do %>
                 <i class="fas fa-link"></i>About
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_registration_path, class: 'nav-link text-light' do %>
                 <i class="fas fa-user-plus"></i>Sign up
                <% end %>
              </li>
              <li class="nav-item">
                <%= link_to new_user_session_path, class: 'nav-link text-light' do %>
                 <i class="fas fa-sign-in-alt"></i>Log in
                <% end %>
              </li>
              <% end %>
            </ul>
          </div>
        </div>
      </nav>
  </header>
  <main class="mb-auto">
    <div>
      <%= flash[:notice] %>
      </div>
    <%= yield %>
  </main>
  <footer>
    <div class="container">
      <div class="row">
        <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>
 </body>
</html>